### ISSUE TITLE
Upload images doesn't work

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#606] opened 2016-08-23 11:15 UTC
An exception `i.getHeaders is not a function` comes from [`ApiClient.postMultipart()`](https://github.com/Lokiedu/libertysoil-site/blob/stable/src/api/client.js#L136)

The reason: `multipart` doesn't work after migration to `koa`.

**Comment by xekc** [comment] 2016-08-23 11:23
@ihork please discuss with @oopscurity for any additional information and come up with a testing plan for this.

**Comment by indeyets** [comment] 2016-09-23 17:36
Duplicate of #441

**Closed by indeyets** 2016-09-23 17:36 UTC
Labels: ! High priority, bug, MUST DO
