### ISSUE TITLE
Change field order, auto-prefill username field

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#158] opened 2016-03-04 20:57 UTC
Currently people confuse "Username" field with their real name. They enter it with space and get confused afterwards.

Our solution:

1. Move "First name" and "Last name" fields to the start, making it the first and the last field in the "Create new account" block (followed by "Password" and "Repeat password" - and then "User name" and "Email" fields).

2. Auto-fill "User name" field with "First name" and "Last name" field content, checking if the name is already taken and appending with numbers (simple 1, 2, 3 is ok). 

3. "User name" field has to remain editable. We only suggest it and allow it to be changed.

**Comment by indeyets** [comment] 2016-03-05 14:17
plus! 0/6

**Comment by indeyets** [comment] 2016-03-05 14:21
What symbols can be added to username?

**Comment by Oopscurity** [comment] 2016-03-05 15:47
plus! 1.29/0

**Comment by indeyets** [comment] 2016-03-05 16:50
I can't reproduce this issue on production. I will try reproduce on staging later because now server is down.

**Comment by indeyets** [comment] 2016-03-05 16:51
plus! 0.37/0.37

**Comment by Oopscurity** [comment] 2016-03-05 19:54
plus! 0.74/0

**Comment by Oopscurity** [comment] 2016-03-06 10:17
plus! 0.28/0

**Comment by Oopscurity** [comment] 2016-03-06 10:24
Added basic implementation there: https://github.com/Lokiedu/libertysoil-site/pull/159

**Comment by voidxnull** [comment] 2016-03-07 16:30
In order to implement real time checking of the username, we need to add a new api method. Let me know when you need it, it'll probably take no more than 30 min.

**Comment by voidxnull** [comment] 2016-03-07 18:28
plus! 1/1 Added an api method for checking if a users exists. Added indices for the `users` table.

**Comment by voidxnull** [comment] 2016-03-07 18:31
Use `checkUserExists` method defined in `api/client.js`.

**Comment by Oopscurity** [comment] 2016-03-07 19:54
plus! 0.21/0

**Comment by indeyets** [comment] 2016-03-08 12:02
@oopscurity after investigation, I've noticed that this validation triggered when capital letter is used in username. And  when letter changed to lowercase warning message disappears.
Can you please check if it's true? validation triggered with Uppercase letters.
Please see attached video for more details.

**Comment by indeyets** [comment] 2016-03-08 12:04
plus! 0.65/0.65

**Comment by Oopscurity** [comment] 2016-03-08 12:17
@ihork yes, it's true. Looks like it's been already fixed in production. See https://lokiedu.slack.com/archives/integration/p1457428896000584 for more info.

**Comment by Oopscurity** [comment] 2016-03-08 20:19
plus! 0/-3.48

**Comment by indeyets** [comment] 2016-03-10 14:15
Fields are ordered as First name, Last name, Username, Password, Repeat password, Email now. But in this task fields should be ordered like First name, Last name, Password, Repeat password, Username, Email. Could you confirm which fields order is correct?
Please see attachment

Also, I've checked that username is auto-filled when enter First name, Last name. And numbers are added to this field when username is already taken.

**Comment by indeyets** [comment] 2016-03-10 14:15
plus! 0.77/0.77

**Comment by Oopscurity** [comment] 2016-03-10 18:35
@ihork 
Current fields' order is correct. It's because that username field is dependent from first and second ones and it is updated by them (runtime advices).
Of course, this solution has already been discussed with client.
Thank you for feedback.

**Comment by indeyets** [comment] 2016-03-11 09:18
Fields order is changed and autofill "Username" field works good

**Comment by indeyets** [comment] 2016-03-11 09:18
plus! 0.38/0.38

**Closed** 2016-08-23 10:37 UTC
Labels: QA check Passed
